import Header from "@/components/Header";
import "./globals.css";
import UsernameInput from "@/components/UsernameInput";

export const metadata = {
  title: "GitHub User Search",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <UsernameInput />
        {children}
      </body>
    </html>
  );
}
