import Header from "@/components/Header";
import "./globals.css";
import UsernameInput from "@/components/UsernameInput";
import { Roboto, Roboto_Mono } from "next/font/google";

export const metadata = {
  title: "GitHub User Search",
  description: "Generated by create next app",
};

const robotoMono = Roboto_Mono({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={robotoMono.className}>
        <Header />
        <UsernameInput />
        {children}
      </body>
    </html>
  );
}
